apiVersion: v1
kind: Service
metadata:
  name: qal-service
  namespace: qal
spec:
  type: ClusterIP
  selector:
    name: qal-nginx
  ports:
  - name: qal-service
    protocol: TCP
    port: 8080
    targetPort: 80